import type { Metadata } from "next";
// import { Afacad } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

// const afacad = Afacad({
//   variable: "--font-afacad",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <div className="fixed w-full">
          <NavBar />
        </div>
        <div className="afacad-local">{children}</div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
